name: SyncMate CI/CD Pipeline

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - main

jobs:

  docker-build-and-push:

    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}

      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}

      JWT_SECRET: ${{ secrets.JWT_SECRET }}

      VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build Frontend Docker Image
        run: |
          docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/syncmate-frontend:latest \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/syncmate-frontend:${{ github.sha }} \
          ./Frontend


      - name: Build Backend Docker Image
        run: |
          docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/syncmate-backend:latest \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/syncmate-backend:${{ github.sha }} \
          ./Backend


      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/syncmate-frontend:latest 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/syncmate-frontend:${{ github.sha }}
      

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/syncmate-backend:latest 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/syncmate-backend:${{ github.sha }}





      # - name: Verify Docker Compose File
      #   run: docker compose config


      - name: Show Docker Images
        run: docker images