name: SyncMate CI Pipeline

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - main

jobs:

  docker-build:

    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}

      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}

      JWT_SECRET: ${{ secrets.JWT_SECRET }}

      VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Show Current Files
        run: ls


      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build Frontend Docker Image
        run: docker build -t syncmate-frontend ./Frontend


      - name: Build Backend Docker Image
        run: docker build -t syncmate-backend ./Backend


      - name: Verify Docker Compose File
        run: docker compose config


      - name: Show Docker Images
        run: docker images